// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4VydFtg9Og-N2jOWCRIqV1_U7XPY6fqc',
    appId: '1:518249660125:web:62e60ed8cb46281d6a2534',
    messagingSenderId: '518249660125',
    projectId: 'live-score-app-4b7bc',
    authDomain: 'live-score-app-4b7bc.firebaseapp.com',
    storageBucket: 'live-score-app-4b7bc.firebasestorage.app',
    measurementId: 'G-CNDENY78ML',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4yiVzLwhiaCYSag3ZEfkxueiwbEDwaVk',
    appId: '1:518249660125:android:84dd79fb4aef1d266a2534',
    messagingSenderId: '518249660125',
    projectId: 'live-score-app-4b7bc',
    storageBucket: 'live-score-app-4b7bc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPKeRO01XhXRfqARPD1uPA6DSY_2WqHZc',
    appId: '1:518249660125:ios:b2339c5611f28d246a2534',
    messagingSenderId: '518249660125',
    projectId: 'live-score-app-4b7bc',
    storageBucket: 'live-score-app-4b7bc.firebasestorage.app',
    iosBundleId: 'com.example.liveScoreFootball',
  );
}
